spring:
#  profiles:
#    active: dev, eureka-1
  #active: dev, property, message, rest, rabbit, rabbit-sender, rabbit-receiver, mpa, security
  application:
    name: service-registry

eureka:
  instance:
    hostname: eureka
  server:
    enable-self-preservation: false
  client:
#    fetch-registry: false
#    register-with-eureka: false
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: http://${other.eureka.host}:${other.eureka.port}/eureka



---
spring:
  profiles: eureka-1

server:
  port: 8762

eureka:
  instance:
    hostname: eureka1

other:
  eureka:
    host: eureka2
    port: 8763


---
spring:
  profiles: eureka-2

server:
  port: 8763

eureka:
  instance:
    hostname: eureka2

other:
  eureka:
    host: eureka1
    port: 8762