spring:
  security:
    user:
      name: veinthrough
      password: 123456
  profiles:
    active: dev, property, message, rabbit, rabbit-listener
    #active: dev, property, message, rest, rabbit, rabbit-sender, rabbit-receiver, mpa, security


---
spring:
  profiles: dev

logging:
  level:
    veinthrough.tacocloud:
      messaging: INFO

server:
  port: 8081



---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost/taco
    username: tacouser
    password: tacopassword

logging:
  level: WARN