taco:
  orders:
    pageSize: 10

  discount:
    codes:
      discount-1: 10
      discount-2: 20

spring:
  profiles:
    active: dev



---
spring:
  profiles: dev

logging:
  level:
    veinthrough.spring.tacocloud:
      web: INFO
      config: INFO



---
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword

logging:
  level:
    veinthrough.spring.tacocloud: WARN