spring:
  profiles:
    active: dev, property, security
    #active: dev, property, message, rest, rabbit, rabbit-sender, rabbit-receiver, mpa, security
  application:
    name: service-app
  data:
    rest:
      base-path: /rest


server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://${other.eureka.host}:${other.eureka.port}/eureka


---
spring:
  profiles: dev

logging:
  level:
    veinthrough.tacocloud.service: INFO



---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost/taco
    username: tacouser
    password: tacopassword

logging:
  level: WARN