spring:
  security:
    user:
      name: veinthrough
      password: 123456
  profiles:
    active: dev, property, rabbit, rabbit-listener
    #active: dev, rabbit, rabbit-sender, rabbit-listener


---
spring:
  profiles: dev

logging:
  level:
    veinthrough.tacocloud:
      messaging: INFO

server:
  port: 8081



---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword

logging:
  level: WARN